# Generated by Django 3.1.14 on 2025-06-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='hours',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='time_slots',
            field=models.TextField(default='09:00-10:00'),
        ),
    ]
