# Generated by Django 3.1.14 on 2025-06-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20250620_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='time_slots',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='duration_hours',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
