CREATE TABLE user (
id INTEGER PRIMARY KEY AUTOINCREMENT,
email VARCHAR(255) NOT NULL UNIQUE,
username LONGTEXT NOT NULL UNIQUE,
password VARCHAR(255) NULL,
auth VARCHAR(255) NOT NULL,
picture VARCHAR(255) NULL,
is_admin INTEGER DEFAULT 0,
createdAt DATETIME NOT NULL
);
