// tests.js
const crosswordSolver = require('./crosswordSolver.js')


// helper: capture console.log output από τη συνάρτηση
function runAndCapture(fn) {
  const logs = []
  const oldLog = console.log
  console.log = (msg='') => logs.push(String(msg))
  try { fn() } finally { console.log = oldLog }
  return logs.join('\n')
}

function test(name, fn, expected) {
  const out = runAndCapture(fn)
  const ok = out === expected
  const status = ok ? '✓' : '✗'
  console.log(`${status} ${name}`)
  if (!ok) {
    console.log('--- expected ---')
    console.log(expected)
    console.log('---   got    ---')
    console.log(out)
    process.exitCode = 1
  }
}

// --- SUCCESS CASES ---
test('ex1 basic',
  () => crosswordSolver('2001\n0..0\n1000\n0..0', ['casa','alan','ciao','anta']),
`casa
i..l
anta
o..n`)

const puzzleBig = `...1...........
..1000001000...
...0....0......
.1......0...1..
.0....100000000
100000..0...0..
.0.....1001000.
.0.1....0.0....
.10000000.0....
.0.0......0....
.0.0.....100...
...0......0....
..........0....`

test('ex2 summer set',
  () => crosswordSolver(puzzleBig, [
    'sun','sunglasses','suncream','swimming','bikini','beach',
    'icecream','tan','deckchair','sand','seaside','sandals',
  ]),
`...s...........
..sunglasses...
...n....u......
.s......n...s..
.w....deckchair
bikini..r...n..
.m.....seaside.
.m.b....a.a....
.icecream.n....
.n.a......d....
.g.c.....tan...
...h......l....
..........s....`)

test('ex3 groceries',
  () => crosswordSolver(`..1.1..1...
10000..1000
..0.0..0...
..1000000..
..0.0..0...
1000..10000
..0.1..0...
....0..0...
..100000...
....0..0...
....0......`,
    ['popcorn','fruit','flour','chicken','eggs','vegetables','pasta','pork','steak','cheese']),
`..p.f..v...
flour..eggs
..p.u..g...
..chicken..
..o.t..t...
pork..pasta
..n.s..b...
....t..l...
..cheese...
....a..s...
....k......`)

test('ex4 reversed still unique',
  () => crosswordSolver(puzzleBig, [
    'sun','sunglasses','suncream','swimming','bikini','beach',
    'icecream','tan','deckchair','sand','seaside','sandals',
  ].reverse()),
`...s...........
..sunglasses...
...n....u......
.s......n...s..
.w....deckchair
bikini..r...n..
.m.....seaside.
.m.b....a.a....
.icecream.n....
.n.a......d....
.g.c.....tan...
...h......l....
..........s....`)

// --- ERROR CASES ---
function expectError(name, pzl, wrds) {
  test(name, () => crosswordSolver(pzl, wrds), 'Error')
}

expectError('mismatch words vs slots', '2001\n0..0\n2000\n0..0', ['casa','alan','ciao','anta'])
expectError('start > 2', '0001\n0..0\n3000\n0..0', ['casa','alan','ciao','anta'])
expectError('duplicate word', '2001\n0..0\n1000\n0..0', ['casa','casa','ciao','anta'])
expectError('empty puzzle', '', ['casa','alan','ciao','anta'])
expectError('wrong puzzle type', 123, ['casa','alan','ciao','anta'])
expectError('wrong words type', '2001\n0..0\n1000\n0..0', 123)
expectError('multiple solutions', '2000\n0...\n0...\n0...', ['abba','assa'])
expectError('no solution', '2001\n0..0\n1000\n0..0', ['aaab','aaac','aaad','aaae'])
