FROM fedora:latest
COPY ./software_install.sh /si
COPY ./software_list /sl
COPY ./.gitconfig /root/.gitconfig
COPY ./.git-credentials /root/.git-credentials
RUN /si
RUN sudo chsh -s /usr/bin/zsh
WORKDIR /root
RUN curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
RUN [ -s "$HOME/.nvm/nvm.sh" ] && . "$HOME/.nvm/nvm.sh" && nvm install v22.15.0
# RUN [ -s "$HOME/.nvm/bash_completion" ] && . "$HOME/.nvm/bash_completion"
# RUN source ~/.bashrc && nvm install v22.15.0
RUN wget https://go.dev/dl/go1.25.0.linux-amd64.tar.gz
RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go1.25.0.linux-amd64.tar.gz
RUN git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell
ENV TERM=xterm-256color
EXPOSE 8181
ENTRYPOINT /root/vd/image/entry_point.sh
